apiVersion: 1
contactPoints:
  - orgId: 1
    name: admin-email
    receivers:
      - uid: email1
        type: email
        settings:
          addresses: admin@portsentinel.local
policies:
  - orgId: 1
    receiver: admin-email
    group_by: ['grafana_folder', 'alertname']
