apiVersion: 1

datasources:
  - name: InfluxDB
    uid: portsentinel-influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG:-sentinel}
      defaultBucket: ${INFLUXDB_BUCKET:-traffic}
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
